on:
  workflow_call:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        USER_EMAIL: BotServiceAutomation@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GH_BS_TOKEN }}
